version: '3.8'

services:
  app:
    build:
      context: .
      target: builder
    env_file:
      - .env
    networks:
      - todo-network
    command: npm run test

  mongodb:
    image: mongo:6
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
